export const TYPES = {
  ADD_TO_CAR: "ADD_TO_CAR",
  REMOVE_ONE_FROM_CAR: "REMOVE_ONE_FROM_CAR",
  REMOVE_ALL_FROM_CAR: "REMOVE_ALL_FROM_CAR",
  CLEAR_CAR: "CLEAR_CAR",
  ADD_TO_CAR2: "ADD_TO_CAR2",
  REMOVE_ONE_FROM_CAR2: "REMOVE_ONE_FROM_CAR2",
  REMOVE_ALL_FROM_CAR2: "REMOVE_ALL_FROM_CAR2",
  CLEAR_CAR2: "CLEAR_CAR2",
};
